# Generated by Django 5.2.7 on 2026-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_business_created_by_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
