# Generated by Django 5.2.7 on 2026-03-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_businesses', to='api.user'),
        ),
    ]
